services:
  app:
    container_name: "app"
    build:
      context: "${APPLICATION_ROOT}"
      dockerfile: ".github/actions/images/app/Dockerfile"
      target: app
      args:
        PHP_VERSION: "${TEST_PHP_VERSION:-8.2}"
    image: "${PHP_IMAGE:-itsm-tests-app:local}"
    working_dir: "/var/itsm"
    command: ["sleep", "infinity"]
    environment:
      TEST_DB_NAME: "${TEST_DB_NAME:-glpi}"
      TEST_DB_TYPE: "${TEST_DB_TYPE:-mysql}"
      CODE_COVERAGE: "${CODE_COVERAGE:-false}"
    volumes:
      - "${APPLICATION_ROOT}:/var/itsm:z"
      - "${APP_CONTAINER_HOME}:/home/itsm:z"
